sudo: false # use containers

addons:
  apt_packages:
    - pandoc

before_install:
- tar -xf ./travis/texlive2015.tar
- chmod u+x ./travis/build.sh
- chmod u+x ./travis/publish.sh

script: "./travis/build.sh"

after_success:
- "./travis/publish.sh"

env:
  global:
  - secure: L93vE7kiLxZKrd5dtUumOe3m5Z+eWqW+uiNpHQ9mTITfrerLYSAK4rtcmOi3PD2u6t3hUOrRCX+DgV2YMU9K884nd+GQIc9yMN5Pfq3JkljHNlnfypkiwrkRg25tB5i76oj35D0tvIFTAmOrMEh0Gbu7hUSpwD8wO+1QwaT9QuEESCgBELSlLv7onGam38SvDBs05ZEr2WKRg7DZW1Ch62i/fq4mj+KzjVWuNE/K+/qh8Pz7jbICRcMErxPnI5ctJM4mC+E3F4AE/Tj6Q6iL0MwYxlts+TBOoZC/btyIS1f1d7HxRsQkYGDIAwgnF4gvvMYJQ9CM8ZwHZSUPuosYP5+xHE0CqyHtE4peJBbL9jQOjfZj0xYWP/wSI3+fM8hc4sndSglNi37fMijiBJZU7eBAY9S+QS80qtKMHkXrHyvEc2M8x0z4BHBfq5/GHOPm2CEy/fstLo/yiAeq1AiRlaibteSzfmNgd0Phk9hhrcfm87MaWqvzR5rXSN/o8T0/q2uo8cNqdpF+SFa52/zjTQyi9eZr4qXGvMBok51N8k/9K3OJ03sbxi3w61ejK7wBzDaRHd7eW+bmPqrYHZ2Eq5WY0MPj9xIpNbuaJ89ad/Loqy3MU7aazRwW692QOk5b+pBDPOl+7vEdLxTe+5MF3dW0s+Wom827EOBY4RSUzgs=
  - GH_USER_NAME: fhnw-foliage-engine
  - GH_PROJECT_NAME: foliage-engine-documentation
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/thesis.pdf
  - TZ="Europe/Zurich"
